# Check data for both studies
cat("=== Study S2A Data ===\n")
d0a <- read.csv("S2A/StudyS2A.csv", check.names=F)
cat("Total rows:", nrow(d0a), "\n")
cat("Encouragement split:\n")
print(table(d0a$encouragement))
cat("\nGender feedback by encouragement:\n")
print(table(d0a$gender_feedback, d0a$encouragement))

cat("\n=== Female Selection Rates (S2A) ===\n")
cat("Panel A (No encouragement):\n")
cat("  Control (no gender fb):", round(mean(d0a$female[d0a$encouragement==0 & d0a$gender_feedback==0])*100,1), "%\n")
cat("  Treatment (gender fb):", round(mean(d0a$female[d0a$encouragement==0 & d0a$gender_feedback==1])*100,1), "%\n")
cat("Panel B (With encouragement):\n")
cat("  Control (no gender fb):", round(mean(d0a$female[d0a$encouragement==1 & d0a$gender_feedback==0])*100,1), "%\n")
cat("  Treatment (gender fb):", round(mean(d0a$female[d0a$encouragement==1 & d0a$gender_feedback==1])*100,1), "%\n")

cat("\n\n=== Study S2B Data ===\n")
d0b <- read.csv("S2B/StudyS2B.csv", check.names=F)
cat("Total rows:", nrow(d0b), "\n")
cat("Encouragement split:\n")
print(table(d0b$encouragement))
cat("\nGender feedback by encouragement:\n")
print(table(d0b$gender_feedback, d0b$encouragement))

cat("\n=== Female Selection Rates (S2B) ===\n")
cat("Panel A (No encouragement):\n")
cat("  Control (no gender fb):", round(mean(d0b$female[d0b$encouragement==0 & d0b$gender_feedback==0])*100,1), "%\n")
cat("  Treatment (gender fb):", round(mean(d0b$female[d0b$encouragement==0 & d0b$gender_feedback==1])*100,1), "%\n")
cat("Panel B (With encouragement):\n")
cat("  Control (no gender fb):", round(mean(d0b$female[d0b$encouragement==1 & d0b$gender_feedback==0])*100,1), "%\n")
cat("  Treatment (gender fb):", round(mean(d0b$female[d0b$encouragement==1 & d0b$gender_feedback==1])*100,1), "%\n")
